name: Set-Up

on:
  push:
    branches:
      - master

  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  run-bash-command:
    runs-on: self-hosted  

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install ffmpeg
        run: |
          sudo apt update > /dev/null 2>&1
          sudo apt install -y ffmpeg > /dev/null 2>&1

      - name: Verify ffmpeg Installation
        run: ffmpeg -version
        
      - name: Change Directory to /var/app
        run: cd /var/app

      - name: Clone Repository
        run: git clone https://github.com/${{ github.repository }}.git
        
